name: Feature request
description: Suggest an idea for Youtuber's Dex
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: >
        Thank you for suggesting new features!

        Before filling this, try to contact us about the idea you have.

        ### If you are using the official Youtuber's Dex 

        Join the [official Discord server](https://discord.gg/QweGYRdAqh) and create a post in the
        [`suggestions` forum](https://discord.com/channels/1519033023947870389/1553466082080063679).

        ### If you are hosting your own bot

        Join the [developers server](https://discord.gg/QweGYRdAqh) and create a post in the  [`suggestions` forum]
        (https://discord.com/channels/1519033023947870389/1553466082080063679) .

        ---

        Then, please fill the following information.

  - type: dropdown
    id: selfhosting
    attributes:
      label: Self-hosting
      description: Are you using the official Youtuber's Dex or hosting your own instance?
      options:
        - Official Youtuber's Dex
        - Self-hosting
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true
